# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "youmakemyheartgui"
version = "0.0.1"
authors = [
  { name="J G", email="jwglazebrook@gmail.com" },
]
description = "A simple GUI library that caputers the heart"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

# LIST YOUR DEPENDENCIES HERE
dependencies = [
    "pyqt6",
    "cssutils"
]

[project.urls]
"Homepage" = "https://github.com/John-Glazebrook/youmakemyheartgui"